import { useEffect, useState } from 'react'
import type { WorkflowState } from '../domain/workflow'
import { analyzeAppeal, getWorkflow, recommendAppeal } from './firebaseApi'
import { AppealDetails } from './AppealDetails'

export function AppealReviewerWorkspace({ cycleId }: { cycleId: string }) {
  const [workflow, setWorkflow] = useState<WorkflowState | null>(null)
  const [message, setMessage] = useState('טוען ערעורים…')
  const [pending, setPending] = useState(false)
  const [recommendation, setRecommendation] = useState<Record<string, { outcome: 'approve' | 'reject' | 'more_information'; reason: string }>>({})
  async function refresh() { const value = await getWorkflow(cycleId, 'appeal_reviewer'); setWorkflow(value); setMessage('הערעורים מעודכנים.') }
  useEffect(() => { let active = true; void getWorkflow(cycleId, 'appeal_reviewer').then((value) => { if (active) { setWorkflow(value); setMessage('הערעורים מעודכנים.') } }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : 'הטעינה נכשלה') }); return () => { active = false } }, [cycleId])
  async function analyze(id: string) { try { setPending(true); setWorkflow(await analyzeAppeal(cycleId, id)); setMessage('ניתוח ההשפעה נשמר.') } catch (error) { setMessage(error instanceof Error ? error.message : 'הניתוח נכשל') } finally { setPending(false) } }
  async function saveRecommendation(id: string) { const value = recommendation[id]; if (!value?.reason.trim()) return; try { setPending(true); setWorkflow(await recommendAppeal(cycleId, id, value.outcome, value.reason)); setMessage('המלצת הצוות נשמרה ותוצג לרכז השיבוץ.') } catch (error) { setMessage(error instanceof Error ? error.message : 'שמירת ההמלצה נכשלה') } finally { setPending(false) } }
  return <section className="workspace-card" aria-labelledby="review-title"><div className="workspace-heading"><div><span className="eyebrow">צוות בחינת ערעורים</span><h2 id="review-title">ערעורים לבדיקה</h2></div></div><p className="workspace-message" aria-live="polite">{message}</p>{workflow?.appeals.length ? workflow.appeals.map((appeal) => { const draft = recommendation[appeal.id] ?? { outcome: 'approve' as const, reason: '' }; return <article className="appeal-card" key={appeal.id}><AppealDetails appeal={appeal} />{!appeal.analysis && <button type="button" className="primary-action" disabled={pending} onClick={() => void analyze(appeal.id)}>הפקת ניתוח השפעה</button>}{appeal.status === 'submitted' && <div className="recommendation-form"><h4>המלצת הצוות</h4><label>המלצה<select value={draft.outcome} onChange={(event) => setRecommendation((current) => ({ ...current, [appeal.id]: { ...draft, outcome: event.target.value as typeof draft.outcome } }))}><option value="approve">להמליץ לאשר</option><option value="reject">להמליץ לדחות</option><option value="more_information">לבקש מידע נוסף</option></select></label><label>נימוק<textarea rows={3} value={draft.reason} onChange={(event) => setRecommendation((current) => ({ ...current, [appeal.id]: { ...draft, reason: event.target.value } }))} /></label><button type="button" className="primary-action" disabled={pending || !draft.reason.trim()} onClick={() => void saveRecommendation(appeal.id)}>שמירת המלצה</button>{appeal.recommendation && <p>המלצה קודמת: {appeal.recommendation.reason}</p>}</div>}</article> }) : <p>אין כרגע ערעורים לבדיקה.</p>}<div className="workspace-actions"><button type="button" className="secondary-action" disabled={pending} onClick={() => void refresh()}>רענון</button></div></section>
}
