import { useEffect, useState } from 'react'
import type { AssignmentCycle, CycleStatus } from '../domain/cycle'
import type { AiPriority } from '../domain/assignmentEngine'
import type { AuditEvent } from '../domain/types'
import type { AiEvaluation, WorkflowState } from '../domain/workflow'
import { analyzeAppeal, approveAiEvaluation, approveAssignmentRun, approveCapacityOverride, decideAppeal, executeAppealChange, generateAiEvaluations, getCycle, getCycleCatalog, getWorkflow, listAuditEvents, publishAssignments, runAssignment, transitionCycle } from './firebaseApi'
import { AppealDetails } from './AppealDetails'
import { emulatorMode } from '../infrastructure/firebase/client'

const statusLabels: Record<CycleStatus, string> = { draft: 'טיוטה', choice_open: 'בחירה פתוחה', choice_closed: 'בחירה סגורה', assignment: 'בתהליך שיבוץ', published: 'פורסם', appeals: 'תקופת ערעורים', closed: 'נסגר' }
const actions: Partial<Record<CycleStatus, { to: CycleStatus; label: string; reason: string }>> = {
  draft: { to: 'choice_open', label: 'פתיחת הבחירה', reason: 'פתיחת הבחירה בידי רכז' }, choice_open: { to: 'choice_closed', label: 'סגירת הבחירה', reason: 'סיום תקופת הבחירה' }, choice_closed: { to: 'assignment', label: 'מעבר לשיבוץ', reason: 'פלטי AI נבדקו והקלט מוכן לשיבוץ' }, published: { to: 'appeals', label: 'פתיחת ערעורים', reason: 'פתיחת חלון הערעורים' }, appeals: { to: 'closed', label: 'סגירת המחזור', reason: 'סיום הטיפול בערעורים' },
}
const auditLabels: Record<string, string> = {
  'cycle.created': 'מחזור נוצר', 'catalog.saved': 'הקורסים נשמרו', 'cycle.transitioned': 'מצב המחזור השתנה',
  'preference.draft.saved': 'טיוטת בחירה נשמרה', 'preference.submitted': 'טופס בחירה הוגש', 'ai.batch.generated': 'הערכות נוצרו',
  'ai.evaluation.approved': 'הערכת העדפות אושרה', 'assignment.run.executed': 'השיבוץ הורץ', 'assignment.run.approved': 'השיבוץ אושר',
  'assignment.published': 'השיבוץ פורסם', 'appeal.submitted': 'ערעור הוגש', 'appeal.impact_analyzed': 'השפעת ערעור נבדקה',
  'appeal.recommended': 'נשמרה המלצה לערעור', 'appeal.approved': 'ערעור אושר כהצעה', 'appeal.rejected': 'ערעור נדחה',
  'appeal.capacity_override.approved': 'חריגת קיבולת אושרה', 'appeal.change.executed': 'שינוי בעקבות ערעור בוצע',
}
async function loadWorkspace(cycleId: string) { const [cycle, audits, workflow, catalog] = await Promise.all([getCycle(cycleId), listAuditEvents(), getWorkflow(cycleId, 'coordinator'), getCycleCatalog(cycleId)]); return { cycle, audits, workflow, catalog } }

function EvaluationEditor({ evaluation, cycleId, clusterLabel, onSaved }: { evaluation: AiEvaluation; cycleId: string; clusterLabel: string; onSaved: (workflow: WorkflowState) => void }) {
  const [priority, setPriority] = useState<AiPriority>(evaluation.approved?.priority ?? evaluation.raw.priority)
  const [summary, setSummary] = useState(evaluation.approved?.summary ?? evaluation.raw.summary)
  const [pending, setPending] = useState(false)
  async function save() { setPending(true); try { onSaved(await approveAiEvaluation(cycleId, evaluation.id, priority, summary)) } finally { setPending(false) } }
  return <article className="workflow-item"><div><strong>מזהה אנונימי: {evaluation.anonymousStudentRef.slice(0, 13)}…</strong><small>{clusterLabel}</small></div><p>{evaluation.input.rationale ?? 'לא נמסר נימוק — הערכה ניטרלית.'}</p><label>עדיפות מאושרת<select value={priority} onChange={(event) => setPriority(event.target.value as AiPriority)}><option value="high">גבוהה</option><option value="medium">בינונית</option><option value="neutral">ניטרלית</option></select></label><label>סיכום לצוות<textarea rows={2} value={summary} onChange={(event) => setSummary(event.target.value)} /></label><button type="button" className="secondary-action" disabled={pending} onClick={() => void save()}>{evaluation.approved ? 'עדכון אישור' : 'אישור פלט'}</button></article>
}

export function CoordinatorWorkflowWorkspace({ cycleId }: { cycleId: string }) {
  const [cycle, setCycle] = useState<AssignmentCycle | null>(null); const [workflow, setWorkflow] = useState<WorkflowState | null>(null); const [audits, setAudits] = useState<AuditEvent[]>([]); const [courseLabels, setCourseLabels] = useState<Record<string, string>>({}); const [clusterLabels, setClusterLabels] = useState<Record<string, string>>({}); const [message, setMessage] = useState('טוען את לוח המחזור…'); const [pending, setPending] = useState(false)
  function applyLoaded(loaded: Awaited<ReturnType<typeof loadWorkspace>>) { setCycle(loaded.cycle); setAudits(loaded.audits); setWorkflow(loaded.workflow); setCourseLabels(Object.fromEntries(loaded.catalog.courses.map((course) => [course.id, course.label]))); setClusterLabels(Object.fromEntries((loaded.catalog.catalog?.clusters ?? []).map((cluster) => [cluster.clusterId, cluster.label]))) }
  async function refresh() { const loaded = await loadWorkspace(cycleId); applyLoaded(loaded); setMessage('הנתונים מעודכנים.') }
  useEffect(() => { let active = true; void loadWorkspace(cycleId).then((loaded) => { if (active) { applyLoaded(loaded); setMessage('הנתונים מעודכנים.') } }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : 'טעינת המחזור נכשלה') }); return () => { active = false } }, [cycleId])
  async function perform(operation: () => Promise<unknown>, success: string) { if (pending) return; try { setPending(true); await operation(); await refresh(); setMessage(success) } catch (error) { setMessage(error instanceof Error ? error.message : 'הפעולה נכשלה') } finally { setPending(false) } }
  if (!cycle || !workflow) return <section className="workspace-card"><p aria-live="polite">{message}</p></section>
  const action = actions[cycle.status]; const allAiApproved = workflow.aiEvaluations.length > 0 && workflow.aiEvaluations.every((entry) => entry.approved)
  return <section className="workspace-card" aria-labelledby="coordinator-title">
    <div className="workspace-heading"><div><span className="eyebrow">אזור רכז שיבוץ</span><h2 id="coordinator-title">לוח המחזור</h2></div><span className="status-pill">{statusLabels[cycle.status]}</span></div><p className="workspace-message" aria-live="polite">{message}</p>
    <dl className="workspace-metrics"><div><dt>שנת לימודים</dt><dd>{cycle.schoolYear}</dd></div><div><dt>תקופה</dt><dd>{cycle.termLabel}</dd></div><div><dt>הערכות AI שאושרו</dt><dd>{workflow.aiEvaluations.filter((entry) => entry.approved).length}/{workflow.aiEvaluations.length}</dd></div><div><dt>ערעורים</dt><dd>{workflow.appeals.length}</dd></div></dl>
    {['choice_closed', 'assignment'].includes(cycle.status) && <div className="workflow-section"><div className="section-heading compact"><div><h3>בדיקה ואישור לפני השיבוץ</h3></div>{!workflow.aiBatchCreatedAt && emulatorMode && <button type="button" className="primary-action" disabled={pending} onClick={() => void perform(() => generateAiEvaluations(cycleId), 'ההערכות נוצרו ומוכנות לבדיקה.')}>יצירת הערכות</button>}</div>{!workflow.aiBatchCreatedAt && !emulatorMode && <p>שירות הערכת ההעדפות עדיין אינו זמין.</p>}{workflow.aiEvaluations.map((evaluation) => <EvaluationEditor key={evaluation.id} evaluation={evaluation} cycleId={cycleId} clusterLabel={clusterLabels[evaluation.clusterId] ?? 'מקבץ'} onSaved={(updated) => { setWorkflow(updated); setMessage('ההערכה נשמרה.') }} />)}</div>}
    {cycle.status === 'assignment' && <div className="workflow-section"><h3>הרצת שיבוץ</h3>{!workflow.assignmentRun ? <button type="button" className="primary-action" disabled={!allAiApproved || pending} onClick={() => void perform(() => runAssignment(cycleId), 'השיבוץ הושלם והתוצאות מוכנות לבדיקה.')}>הרצת השיבוץ</button> : <><p>{workflow.assignmentRun.assignments.length} שיבוצים · {workflow.assignmentRun.warnings.length} אזהרות</p><ul>{workflow.assignmentRun.assignments.map((entry) => <li key={`${entry.studentId}-${entry.clusterId}`}>{entry.studentLabel ?? 'תלמיד'} · {clusterLabels[entry.clusterId] ?? 'מקבץ'} ← <strong>{courseLabels[entry.courseId] ?? 'קורס'}</strong></li>)}</ul>{!workflow.assignmentRun.approvedAt ? <button type="button" className="primary-action" disabled={pending} onClick={() => void perform(() => approveAssignmentRun(cycleId), 'השיבוץ אושר ומוכן לפרסום.')}>אישור השיבוץ</button> : <button type="button" className="primary-action" disabled={pending} onClick={() => void perform(() => publishAssignments(cycleId), 'השיבוץ פורסם והדיווחים הוכנו לשליחה.')}>פרסום השיבוץ</button>}</>}</div>}
    {workflow.appeals.length > 0 && <div className="workflow-section"><h3>ערעורים ושינויים מוצעים</h3>{workflow.appeals.map((appeal) => <article className="appeal-card" key={appeal.id}><AppealDetails appeal={appeal} />{!appeal.analysis && <button type="button" className="secondary-action" disabled={pending} onClick={() => void perform(() => analyzeAppeal(cycleId, appeal.id), 'ניתוח ההשפעה נשמר.')}>ניתוח השפעה</button>}{appeal.analysis && appeal.status === 'submitted' && <div className="workspace-actions"><button type="button" className="primary-action" disabled={pending || appeal.analysis.constraintViolations.some((violation) => !violation.includes('קיבולת המרבית'))} onClick={() => void perform(() => decideAppeal(cycleId, appeal.id, 'approved'), 'הערעור אושר כהצעה בלבד; השיבוץ טרם השתנה.')}>אישור הערעור כהצעה</button><button type="button" className="secondary-action" disabled={pending} onClick={() => void perform(() => decideAppeal(cycleId, appeal.id, 'rejected'), 'הערעור נדחה ותועד.')}>דחייה</button></div>}{appeal.status === 'approved_pending_execution' && appeal.analysis?.requiresMovingAnotherStudent && !appeal.capacityOverride && <button type="button" className="secondary-action" disabled={pending} onClick={() => void perform(() => approveCapacityOverride(cycleId, appeal.id), 'אישור חריגת הקיבולת נשמר. רכז אחר יוכל לבצע את השינוי.')}>אישור חריגת קיבולת</button>}{appeal.status === 'approved_pending_execution' && (!appeal.analysis?.requiresMovingAnotherStudent || appeal.capacityOverride) && <button type="button" className="primary-action" disabled={pending} onClick={() => void perform(() => executeAppealChange(cycleId, appeal.id, workflow.version), 'השינוי בוצע. הדיווחים הועברו למזכירות ולתלמיד.')}>אישור מפורש וביצוע השינוי</button>}</article>)}</div>}
    <div className="workspace-actions">{action && <button type="button" className="primary-action" disabled={pending || (cycle.status === 'choice_closed' && !allAiApproved)} onClick={() => void perform(() => transitionCycle(cycle, action.to, action.reason), `הפעולה “${action.label}” בוצעה ונשמרה.`)}>{action.label}</button>}<button type="button" className="secondary-action" onClick={() => void refresh()}>רענון נתונים</button></div>
    <div className="audit-preview"><h3>פעולות אחרונות</h3>{audits.length ? <ol>{audits.slice(0, 5).map((event) => <li key={event.id}><strong>{auditLabels[event.action] ?? 'פעולה במערכת'}</strong><span>{new Date(event.occurredAt).toLocaleString('he-IL')}</span>{event.reason && <small>{event.reason}</small>}</li>)}</ol> : <p>עדיין לא נרשמו פעולות.</p>}</div>
  </section>
}
