import { ResultDelivery } from './ResultDelivery'
import { useReadOnly } from './readOnly'
import { useEffect, useState } from 'react'
import type { AssignmentCycle, CycleStatus } from '../domain/cycle'
import type { AiPriority } from '../domain/assignmentEngine'
import type { AuditEvent } from '../domain/types'
import type { AiEvaluation, WorkflowState } from '../domain/workflow'
import { needsIndividualAiReview } from '../domain/aiReview'
import { rejectAssignmentRun, analyzeAppeal, approveAiEvaluation, approveAiEvaluations, approveAssignmentRun, approveCapacityOverride, decideAppeal, executeAppealChange, generateAiEvaluations, getCycle, getCycleCatalog, getWorkflow, listAuditEvents, publishAssignments, transitionCycle } from './firebaseApi'
import { AppealDetails } from './AppealDetails'
import { AssignmentScenarioPlanner } from './AssignmentScenarioPlanner'
import { StudentRoster } from './StudentRoster'
import { ManualAssignmentChange } from './ManualAssignmentChange'
import type { Course } from '../domain/catalog'
import { useConfirmAction, useUnsavedChanges } from './interaction'

const statusLabels: Record<CycleStatus, string> = { draft: 'טיוטה', choice_open: 'בחירה פתוחה', choice_closed: 'בחירה סגורה', assignment: 'בתהליך שיבוץ', published: 'פורסם', appeals: 'תקופת ערעורים', closed: 'נסגר' }
const actions: Partial<Record<CycleStatus, { to: CycleStatus; label: string; reason: string }>> = {
  choice_open: { to: 'choice_closed', label: 'סגירת הבחירה', reason: 'סיום תקופת הבחירה' }, choice_closed: { to: 'assignment', label: 'מעבר לשיבוץ', reason: 'פלטי AI נבדקו והקלט מוכן לשיבוץ' }, published: { to: 'appeals', label: 'פתיחת ערעורים', reason: 'פתיחת חלון הערעורים' }, appeals: { to: 'closed', label: 'סגירת המחזור', reason: 'סיום הטיפול בערעורים' },
}
const auditLabels: Record<string, string> = {
  'cycle.created': 'מחזור נוצר', 'catalog.saved': 'הקורסים נשמרו', 'cycle.transitioned': 'מצב המחזור השתנה',
  'preference.draft.saved': 'טיוטת בחירה נשמרה', 'preference.submitted': 'טופס בחירה הוגש', 'ai.batch.generated': 'הערכות נוצרו',
  'ai.evaluation.approved': 'הערכת העדפות אושרה', 'assignment.run.executed': 'השיבוץ הורץ', 'assignment.run.approved': 'השיבוץ אושר',
  'assignment.run.selected': 'נבחרה גרסת שיבוץ', 'assignment.rejected': 'גרסת שיבוץ נדחתה',
  'assignment.published': 'השיבוץ פורסם', 'appeal.submitted': 'ערעור הוגש', 'appeal.impact_analyzed': 'השפעת ערעור נבדקה',
  'appeal.recommended': 'נשמרה המלצה לערעור', 'appeal.approved': 'ערעור אושר כהצעה', 'appeal.rejected': 'ערעור נדחה',
  'appeal.capacity_override.approved': 'חריגת קיבולת אושרה', 'appeal.change.executed': 'שינוי בעקבות ערעור בוצע',
  'assignment.manual_change.executed': 'שיבוץ תלמיד שונה ידנית',
}
async function loadWorkspace(cycleId: string) { const [cycle, audits, workflow, catalog] = await Promise.all([getCycle(cycleId), listAuditEvents(), getWorkflow(cycleId, 'coordinator'), getCycleCatalog(cycleId)]); return { cycle, audits, workflow, catalog } }

function EvaluationEditor({ evaluation, cycleId, clusterLabel, onSaved }: { evaluation: AiEvaluation; cycleId: string; clusterLabel: string; onSaved: (workflow: WorkflowState) => void }) {
  const readOnly = useReadOnly()
  const [priority, setPriority] = useState<AiPriority>(evaluation.approved?.priority ?? evaluation.raw.priority)
  const [summary, setSummary] = useState(evaluation.approved?.summary ?? evaluation.raw.summary)
  const initialCoursePriorities = evaluation.approved?.coursePriorities ?? evaluation.raw.coursePriorities
  const [coursePriorities, setCoursePriorities] = useState<Record<string, AiPriority>>(() => Object.fromEntries(initialCoursePriorities?.map((course) => [course.courseId, course.priority]) ?? []))
  const [pending, setPending] = useState(false)
  const [error, setError] = useState('')
  const hasCourseReview = Boolean(evaluation.raw.coursePriorities)
  const currentPriority: AiPriority = hasCourseReview ? Object.values(coursePriorities).includes('high') ? 'high' : Object.values(coursePriorities).includes('medium') ? 'medium' : 'neutral' : priority
  const courseChanged = Boolean(initialCoursePriorities?.some((course) => coursePriorities[course.courseId] !== course.priority))
  useUnsavedChanges(courseChanged || (!hasCourseReview && priority !== (evaluation.approved?.priority ?? evaluation.raw.priority)) || summary !== (evaluation.approved?.summary ?? evaluation.raw.summary) || pending)
  async function save() { if (pending) return; setPending(true); try { onSaved(await approveAiEvaluation(cycleId, evaluation.id, currentPriority, summary, evaluation.raw.coursePriorities?.map((course) => ({ courseId: course.courseId, priority: coursePriorities[course.courseId] ?? 'neutral' })))); setError('') } catch (failure) { setError(failure instanceof Error ? failure.message : 'שמירת ההערכה נכשלה. יש לרענן ולנסות שוב.') } finally { setPending(false) } }
  return <article className="workflow-item">{error && <p role="alert">{error}</p>}<div><strong>{clusterLabel}</strong><small>מספר בדיקה {evaluation.anonymousStudentRef.slice(5, 13)}</small></div><p>{evaluation.input.rationale ?? 'לא נמסר נימוק — ההמלצה ניטרלית.'}</p>{hasCourseReview ? <div className="evaluation-courses">{evaluation.input.courses?.filter((course) => course.rank !== null).sort((left, right) => (left.rank ?? 0) - (right.rank ?? 0)).map((course) => <div className="evaluation-course" key={course.courseId}><strong>{course.rank}. {course.label}</strong><p>{evaluation.raw.coursePriorities?.find((entry) => entry.courseId === course.courseId)?.reason}</p><label>עדיפות לקורס<select disabled={readOnly} value={coursePriorities[course.courseId] ?? 'neutral'} onChange={(event) => setCoursePriorities((current) => ({ ...current, [course.courseId]: event.target.value as AiPriority }))}><option value="high">גבוהה</option><option value="medium">בינונית</option><option value="neutral">ניטרלית</option></select></label></div>)}</div> : <><p>הערכה קודמת למקבץ כולו; בעת שיבוץ העדיפות תחול על כל הקורסים שדורגו בו.</p><label>עדיפות מאושרת<select disabled={readOnly} value={priority} onChange={(event) => setPriority(event.target.value as AiPriority)}><option value="high">גבוהה</option><option value="medium">בינונית</option><option value="neutral">ניטרלית</option></select></label></>}<label>סיכום לצוות<textarea disabled={readOnly} rows={3} value={summary} onChange={(event) => setSummary(event.target.value)} /></label><button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void save()}>{evaluation.approved ? 'עדכון אישור' : 'אישור ההערכה'}</button></article>
}

export function CoordinatorWorkflowWorkspace({ cycleId, onCycleChanged }: { cycleId: string; onCycleChanged: () => Promise<void> }) {
  const readOnly = useReadOnly()
  const { confirm, confirmation } = useConfirmAction()
  const [tab, setTab] = useState<'overview' | 'students' | 'evaluations' | 'appeals' | 'proposed' | 'actual' | 'delivery'>('overview')
  const [rejectionReason,setRejectionReason]=useState('')
  const [now,setNow]=useState(()=>Date.now())
  const [appealQuery, setAppealQuery] = useState('')
  const [appealStatus, setAppealStatus] = useState('submitted')
  const [evaluationFilter, setEvaluationFilter] = useState('pending')
  const [approvalMode, setApprovalMode] = useState<'individual' | 'exceptions' | 'all'>('individual')
  const [evaluationLimit, setEvaluationLimit] = useState(30)
  const [cycleRevision, setCycleRevision] = useState(0)
  const [courses, setCourses] = useState<Course[]>([])
  const [cycle, setCycle] = useState<AssignmentCycle | null>(null); const [workflow, setWorkflow] = useState<WorkflowState | null>(null); const [audits, setAudits] = useState<AuditEvent[]>([]); const [courseLabels, setCourseLabels] = useState<Record<string, string>>({}); const [clusterLabels, setClusterLabels] = useState<Record<string, string>>({}); const [balancedClusterIds, setBalancedClusterIds] = useState<string[]>([]); const [message, setMessage] = useState('טוען את לוח המחזור…'); const [pending, setPending] = useState(false)
  function applyLoaded(loaded: Awaited<ReturnType<typeof loadWorkspace>>) { setCycle(loaded.cycle); setAudits(loaded.audits); setWorkflow(loaded.workflow); setCourses(loaded.catalog.courses); setCourseLabels(Object.fromEntries(loaded.catalog.courses.map((course) => [course.id, course.label]))); setClusterLabels(Object.fromEntries((loaded.catalog.catalog?.clusters ?? []).map((cluster) => [cluster.clusterId, cluster.label]))); setBalancedClusterIds((loaded.catalog.catalog?.clusters ?? []).filter((cluster) => cluster.balanceByClass).map((cluster) => cluster.clusterId)) }
  async function refresh() { try { const loaded = await loadWorkspace(cycleId); applyLoaded(loaded); setCycleRevision((value) => value + 1); setMessage('הנתונים מעודכנים.') } catch { setMessage('רענון הנתונים נכשל. יש לנסות שוב לפני המשך העבודה.') } }
  useEffect(() => { let active = true; void loadWorkspace(cycleId).then((loaded) => { if (active) { applyLoaded(loaded); setMessage('הנתונים מעודכנים.') } }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : 'טעינת המחזור נכשלה') }); return () => { active = false } }, [cycleId])
  useEffect(() => { const timer=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(timer) },[])
  async function perform(operation: () => Promise<unknown>, success: string) { if (pending) return; let saved = false; try { setPending(true); await operation(); saved = true; await refresh(); await onCycleChanged(); setMessage(success) } catch (error) { setMessage(saved ? 'הפעולה נשמרה, אך רענון הנתונים נכשל. רעננו את המסך ובדקו את המצב לפני ניסיון נוסף.' : error instanceof Error ? error.message : 'הפעולה נכשלה. רעננו ובדקו את המצב לפני ניסיון נוסף.') } finally { setPending(false) } }
  async function selectTab(next: typeof tab) {
    if (next === tab) return
    if (!window.dispatchEvent(new Event('nativ-before-navigation', { cancelable: true })) && !(await confirm('יש שינויים שלא נשמרו. לעבור ללשונית אחרת?'))) return
    setTab(next)
  }
  async function selectApprovalMode(next: typeof approvalMode) {
    if (next === approvalMode) return
    if (!window.dispatchEvent(new Event('nativ-before-navigation', { cancelable: true })) && !(await confirm('יש שינויים שלא נשמרו. לשנות את אופן הצגת ההערכות?'))) return
    setApprovalMode(next)
  }
  async function confirmPerform(operation: () => Promise<unknown>, success: string, question: string) { if (pending || !(await confirm(question))) return; await perform(operation, success) }
  async function confirmBulkApproval(mode: 'clear_only' | 'all', count: number) {
    if (!window.dispatchEvent(new Event('nativ-before-navigation', { cancelable: true })) && !(await confirm('יש שינויים שלא נשמרו בהערכה פתוחה. להמשיך לאישור המרוכז בלעדיהם?'))) return
    await confirmPerform(() => approveAiEvaluations(cycleId, mode, workflow!.version), `אושרו ${count} הערכות. יתר ההערכות ממתינות לבדיקה.`, `לאשר יחד ${count} הערכות${mode === 'all' ? `, כולל ${requiredReviewCount} מקרים שסומנו לבדיקה` : ' שלא סומנו לבדיקה אישית'}?`)
  }
  if (!cycle || !workflow) return <section className="workspace-card"><p aria-live="polite">{message}</p></section>
  const action = actions[cycle.status]; const allAiApproved = workflow.aiEvaluations.length > 0 && workflow.aiEvaluations.every((entry) => entry.approved); const activeRunExclusions=workflow.assignmentRun?.excludedStudentClusterCount??0; const legacyEvaluationCount = workflow.aiEvaluations.filter((entry) => !entry.raw.coursePriorities).length
  const pendingEvaluations = workflow.aiEvaluations.filter((entry) => !entry.approved)
  const requiredReviewCount = pendingEvaluations.filter(needsIndividualAiReview).length
  const clearReviewCount = pendingEvaluations.length - requiredReviewCount
  return <section className="workspace-card" aria-labelledby="coordinator-title">
    <div className="workspace-heading"><div><span className="eyebrow">אזור רכז שיבוץ</span><h2 id="coordinator-title">לוח המחזור</h2></div><span className="status-pill">{cycle.status==='choice_open' && cycle.choiceDeadlineEnabled && cycle.choiceClosesAt && new Date(cycle.choiceClosesAt).getTime() <= now ? 'מועד ההגשה חלף' : statusLabels[cycle.status]}</span></div><p className="workspace-message" aria-live="polite">{message}</p>
    {confirmation}
    <nav className="role-navigation" aria-label="ניהול המחזור">{([['overview', 'תמונת מצב'], ['students', 'תלמידים ובחירות'], ['evaluations', 'בדיקת העדפות'], ['proposed','שיבוץ מוצע'], ['actual','שיבוץ בפועל'], ['appeals', 'ערעורים'], ['delivery','שליחת תוצאות']] as const).map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} aria-pressed={tab === id} onClick={() => void selectTab(id)}>{label}</button>)}</nav>
    {tab === 'overview' && <div className="next-action"><h3>דורש טיפול</h3><p>{cycle.status === 'draft' ? 'הכינו את הטופס ושלחו אותו לתלמידים בלוח הגדרות וטופס.' : cycle.status === 'choice_open' ? (cycle.choiceDeadlineEnabled && cycle.choiceClosesAt && new Date(cycle.choiceClosesAt).getTime() <= now ? 'מועד ההגשה חלף. אפשר להאריך אותו בהגדרות הטופס או לסגור את שלב הבחירה.' : 'תקופת הבחירה פתוחה. אפשר לבדוק מי כבר הגיש ומי עדיין ממתין.') : cycle.status === 'choice_closed' ? (allAiApproved ? 'ההעדפות אושרו. אפשר להתקדם לשיבוץ.' : 'יש להכין ולבדוק את הערכות ההעדפות לפני השיבוץ.') : cycle.status === 'assignment' ? 'יש לבדוק את תוצאות השיבוץ ולאשר אותן לפני הפרסום.' : cycle.status === 'closed' ? 'המחזור הסתיים. אפשר לעיין בבחירות ובשיבוצים.' : 'אפשר לעקוב אחר השיבוצים והערעורים שהתקבלו.'}</p><div className="workspace-actions"><button className="secondary-action" onClick={() => setTab('students')}>צפייה בבחירות</button>{cycle.status==='assignment' && <button className="primary-action" onClick={()=>setTab('proposed')}>בדיקת השיבוץ המוצע</button>}{cycle.status === 'choice_closed' && !allAiApproved && <button className="primary-action" onClick={() => setTab('evaluations')}>בדיקת העדפות</button>}{workflow.appeals.some((entry) => entry.status === 'submitted' || entry.status === 'approved_pending_execution') && <button className="primary-action" onClick={() => setTab('appeals')}>טיפול בערעורים</button>}</div></div>}
    {tab === 'students' && <StudentRoster cycleId={cycleId} courseLabels={courseLabels} clusterLabels={clusterLabels} revision={cycleRevision} />}
    <dl className="workspace-metrics"><div><dt>שנת לימודים</dt><dd>{cycle.schoolYear}</dd></div><div><dt>תקופה</dt><dd>{cycle.termLabel}</dd></div><div><dt>הערכות AI שאושרו</dt><dd>{workflow.aiEvaluations.filter((entry) => entry.approved).length}/{workflow.aiEvaluations.length}</dd></div><div><dt>ערעורים</dt><dd>{workflow.appeals.length}</dd></div></dl>
    {tab === 'evaluations' && workflow.aiBatchCreatedAt && <div className="evaluation-approval-panel"><strong>אישור הערכות</strong><p>{pendingEvaluations.length} ממתינות לאישור · {requiredReviewCount} דורשות בדיקה · {clearReviewCount} מתאימות לאישור מרוכז</p><div className="workspace-actions" role="group" aria-label="דרך אישור ההערכות"><button type="button" className={approvalMode === 'individual' ? 'primary-action' : 'secondary-action'} onClick={() => void selectApprovalMode('individual')}>כל מקרה בנפרד</button><button type="button" className={approvalMode === 'exceptions' ? 'primary-action' : 'secondary-action'} onClick={() => void selectApprovalMode('exceptions')}>בדיקת מקרים נדרשים</button><button type="button" className={approvalMode === 'all' ? 'primary-action' : 'secondary-action'} onClick={() => void selectApprovalMode('all')}>אישור מרוכז</button></div>{approvalMode === 'exceptions' && <><p>מקרים עם נימוק לא ברור, המלצה גבוהה, התאמה ליותר מקורס אחד או הערכה ישנה מופיעים לבדיקה אישית. המלצה בינונית לקורס אחד והגשה ללא נימוק ניתנות לאישור יחד.</p>{clearReviewCount > 0 && <button type="button" className="secondary-action" disabled={readOnly || pending || Boolean(workflow.assignmentRun)} onClick={() => void confirmBulkApproval('clear_only', clearReviewCount)}>אישור {clearReviewCount} הערכות ברורות</button>}</>}{approvalMode === 'all' && <><p>האישור יחול על כל ההערכות הממתינות, כולל {requiredReviewCount} מקרים שסומנו לבדיקה. אישורים פרטניים קיימים לא ישתנו.</p><button type="button" className="primary-action" disabled={readOnly || pending || !pendingEvaluations.length || Boolean(workflow.assignmentRun)} onClick={() => void confirmBulkApproval('all', pendingEvaluations.length)}>אישור כל ההערכות הממתינות</button></>}{workflow.assignmentRun && <p>כבר נוצרה הרצת שיבוץ; אי אפשר לאשר הערכות באופן מרוכז כעת.</p>}</div>}
    {tab === 'evaluations' && ['choice_closed', 'assignment'].includes(cycle.status) && <div className="workflow-section">
      <div className="section-heading compact"><div><h3>בדיקה ואישור לפני השיבוץ</h3></div>
        {!workflow.aiBatchCreatedAt && <button type="button" className="primary-action" disabled={readOnly || pending} onClick={() => void perform(() => generateAiEvaluations(cycleId), 'ההערכות נוצרו ומוכנות לבדיקה.')}>יצירת הערכות</button>}
        {legacyEvaluationCount > 0 && !workflow.assignmentRun && <button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void confirmPerform(() => generateAiEvaluations(cycleId, true), 'המלצות חדשות לפי קורס מוכנות לבדיקה. יש לאשר אותן מחדש לפני השיבוץ.', `ליצור מחדש ${legacyEvaluationCount} הערכות לפי הקורסים? האישורים הקודמים יישמרו בארכיון ויידרש אישור מחדש לפני השיבוץ.`)}>הכנת המלצות לפי קורסים</button>}
      </div>
      {legacyEvaluationCount > 0 && workflow.assignmentRun && <p>הערכות קודמות משמשות בהרצת שיבוץ קיימת. לא ניתן להחליפן בזמן שההרצה קיימת.</p>}
      {pending && <p role="status">מכין הערכות. הפעולה עשויה להימשך כמה דקות.</p>}
      {approvalMode !== 'all' && <><label>הצגת הערכות<select value={evaluationFilter} onChange={(event) => { setEvaluationFilter(event.target.value); setEvaluationLimit(30) }}><option value="pending">ממתינות לאישור</option><option value="all">כל ההערכות</option></select></label>
        {workflow.aiEvaluations.filter((entry) => (evaluationFilter === 'all' || !entry.approved) && (approvalMode !== 'exceptions' || needsIndividualAiReview(entry))).slice(0, evaluationLimit).map((evaluation) => <EvaluationEditor key={`${evaluation.id}:${workflow.version}`} evaluation={evaluation} cycleId={cycleId} clusterLabel={clusterLabels[evaluation.clusterId] ?? 'מקבץ'} onSaved={(updated) => { setWorkflow(updated); setMessage('ההערכה נשמרה.') }} />)}
        {workflow.aiEvaluations.filter((entry) => (evaluationFilter === 'all' || !entry.approved) && (approvalMode !== 'exceptions' || needsIndividualAiReview(entry))).length > evaluationLimit && <button className="secondary-action" onClick={() => setEvaluationLimit((value) => value + 30)}>הצגת הערכות נוספות</button>}
      </>}
    </div>}
    {tab === 'proposed' && cycle.status === 'assignment' && <div className="workflow-section"><AssignmentScenarioPlanner cycleId={cycleId} workflow={workflow} clusterLabels={clusterLabels} readOnly={readOnly} onWorkflow={updated=>{setWorkflow(updated);setCycleRevision(value=>value+1);setMessage('נתוני ההרצות עודכנו.')}}/>{workflow.assignmentRun&&<><div className="selected-run-summary"><h3>{workflow.assignmentRun.label??'ההרצה הפעילה'}</h3><p>{workflow.assignmentRun.assignments.length} שיבוצים · {activeRunExclusions} החרגות · {workflow.assignmentRun.warnings.length} אזהרות</p></div><button className="secondary-action" onClick={() => setTab('students')}>צפייה בשיבוץ לפי תלמיד, כיתה וקורס</button>{balancedClusterIds.length > 0 && <div className="class-balance-summary"><h4>פיזור לפי כיתות</h4>{balancedClusterIds.map((clusterId) => <section key={clusterId}><strong>{clusterLabels[clusterId] ?? 'מקבץ'}</strong>{[...new Set(workflow.assignmentRun!.assignments.filter((entry) => entry.clusterId === clusterId).map((entry) => entry.courseId))].map((courseId) => { const entries = workflow.assignmentRun!.assignments.filter((entry) => entry.clusterId === clusterId && entry.courseId === courseId && entry.studentClassLabel); const counts = entries.reduce<Record<string, number>>((result, entry) => ({ ...result, [entry.studentClassLabel!]: (result[entry.studentClassLabel!] ?? 0) + 1 }), {}); return <p key={courseId}><b>{courseLabels[courseId] ?? 'קורס'}:</b> {Object.entries(counts).length ? Object.entries(counts).map(([classLabel, count]) => `${classLabel} — ${count}`).join(' · ') : 'לא נמצאו נתוני כיתה'}</p> })}</section>)}</div>}{workflow.assignmentRun.warnings.length > 0 && <ul className="warning-list">{workflow.assignmentRun.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>}{!workflow.assignmentRun.approvedAt ? <button type="button" className="primary-action" disabled={readOnly || pending} onClick={() => void perform(() => approveAssignmentRun(cycleId), 'השיבוץ אושר ומוכן לפרסום.')}>אישור ההרצה הפעילה</button> : <button type="button" className="primary-action" disabled={readOnly || pending} onClick={() => void confirmPerform(() => publishAssignments(cycleId), 'השיבוץ פורסם במערכת. ניתן לשלוח תוצאות בנפרד.', `לפרסם את ההרצה הפעילה? היא כוללת ${activeRunExclusions} החרגות והתלמידים יוכלו לראות את התוצאה.`)}>פרסום ההרצה הפעילה</button>}</>}</div>}
    {tab === 'proposed' && !workflow.assignmentRun && cycle.status!=='assignment' && <p>השיבוץ המוצע יהיה זמין לאחר סגירת הבחירה ואישור ההעדפות.</p>}
    {tab === 'proposed' && workflow.assignmentRun && !workflow.assignmentRun.publishedAt && <div className="workflow-section"><label className="rationale-field">סיבה לדחיית ההצעה<textarea value={rejectionReason} onChange={e=>setRejectionReason(e.target.value)} /></label><button className="danger-action" disabled={readOnly||pending||!rejectionReason.trim()} onClick={()=>void confirmPerform(()=>rejectAssignmentRun(cycleId,workflow.version,rejectionReason),'ההצעה נדחתה ונשמרה בהיסטוריה. אפשר לבדוק את ההעדפות וליצור הצעה חדשה.','לדחות את הצעת השיבוץ?')}>דחיית השיבוץ המוצע</button><StudentRoster cycleId={cycleId} courseLabels={courseLabels} clusterLabels={clusterLabels} revision={cycleRevision}/></div>}
    {tab === 'proposed' && workflow.assignmentRun?.publishedAt && <p>השיבוץ אושר ופורסם. ניתן לצפות בו בלשונית שיבוץ בפועל.</p>}
    {tab === 'actual' && (workflow.assignmentRun?.publishedAt ? <><StudentRoster cycleId={cycleId} courseLabels={courseLabels} clusterLabels={clusterLabels} revision={cycleRevision}/><ManualAssignmentChange cycleId={cycleId} workflow={workflow} courses={courses} clusterLabels={clusterLabels} editable={cycle.status !== 'closed'} onChanged={async()=>{await refresh();await onCycleChanged()}} onShowDelivery={()=>setTab('delivery')}/></> : <p>טרם פורסם שיבוץ בפועל. עברו לשיבוץ מוצע כדי לבדוק ולאשר אותו.</p>)}
    {tab === 'delivery' && <ResultDelivery cycleId={cycleId} published={Boolean(workflow.assignmentRun?.publishedAt)}/>}
    {tab === 'appeals' && <div className="workflow-section"><h3>ערעורים ושינויים מוצעים</h3><div className="filter-bar"><label>חיפוש בתוכן הערעור<input value={appealQuery} onChange={(event) => setAppealQuery(event.target.value)} /></label><label>מצב<select value={appealStatus} onChange={(event) => setAppealStatus(event.target.value)}><option value="">כל הערעורים</option><option value="submitted">ממתינים להחלטה</option><option value="approved_pending_execution">ממתינים לביצוע</option><option value="executed">בוצעו</option><option value="rejected">נדחו</option></select></label></div>{!workflow.appeals.length && <p>לא התקבלו ערעורים במחזור זה.</p>}{workflow.appeals.filter((entry) => (!appealStatus || entry.status === appealStatus) && (!appealQuery || entry.reason.includes(appealQuery))).map((appeal) => <article className="appeal-card" key={appeal.id}><AppealDetails appeal={appeal} />{!appeal.analysis && <button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void perform(() => analyzeAppeal(cycleId, appeal.id), 'ניתוח ההשפעה נשמר.')}>ניתוח השפעה</button>}{appeal.analysis && appeal.status === 'submitted' && <div className="workspace-actions"><button type="button" className="primary-action" disabled={readOnly || pending || appeal.analysis.constraintViolations.some((violation) => !violation.includes('קיבולת המרבית'))} onClick={() => void perform(() => decideAppeal(cycleId, appeal.id, 'approved'), 'הערעור אושר כהצעה בלבד; השיבוץ טרם השתנה.')}>אישור הערעור כהצעה</button><button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void perform(() => decideAppeal(cycleId, appeal.id, 'rejected'), 'הערעור נדחה ותועד.')}>דחייה</button></div>}{appeal.status === 'approved_pending_execution' && appeal.analysis?.requiresMovingAnotherStudent && !appeal.capacityOverride && <button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void perform(() => approveCapacityOverride(cycleId, appeal.id), 'אישור חריגת הקיבולת נשמר. רכז אחר יוכל לבצע את השינוי.')}>אישור חריגת קיבולת</button>}{appeal.status === 'approved_pending_execution' && (!appeal.analysis?.requiresMovingAnotherStudent || appeal.capacityOverride) && <button type="button" className="primary-action" disabled={readOnly || pending} onClick={() => void confirmPerform(() => executeAppealChange(cycleId, appeal.id, workflow.version), 'השינוי בוצע במערכת. אפשר לשלוח תוצאות מעודכנות בלשונית השליחה.', 'לבצע את השינוי המאושר בשיבוץ?')}>אישור מפורש וביצוע השינוי</button>}</article>)}</div>}
    {tab === 'appeals' && workflow.appeals.some((entry) => entry.status === 'executed') && <div className="workspace-actions"><button type="button" className="primary-action" onClick={() => setTab('delivery')}>שליחת עדכוני שינוי לתלמידים, למורים ולמזכירות</button></div>}
    <div className="workspace-actions">{tab === 'overview' && action && <button type="button" className="primary-action" disabled={readOnly || pending || (cycle.status === 'choice_closed' && !allAiApproved)} onClick={() => void confirmPerform(() => transitionCycle(cycle, action.to, action.reason), `הפעולה “${action.label}” בוצעה ונשמרה.`, `לבצע ${action.label}? מצב המחזור ישתנה עבור המשתמשים.`)}>{action.label}</button>}<button type="button" className="secondary-action" onClick={() => void refresh()}>רענון נתונים</button></div>
    <details className="audit-preview"><summary>פעולות אחרונות</summary>{audits.length ? <ol>{audits.slice(0, 5).map((event) => <li key={event.id}><strong>{auditLabels[event.action] ?? 'פעולה במערכת'}</strong><span>{new Date(event.occurredAt).toLocaleString('he-IL')}</span>{event.reason && <small>{event.reason}</small>}</li>)}</ol> : <p>עדיין לא נרשמו פעולות.</p>}</details>
  </section>
}
