import { useReadOnly } from './readOnly'
import { useEffect, useState } from 'react'
import type { AssignmentCycle, CycleStatus } from '../domain/cycle'
import type { AiPriority } from '../domain/assignmentEngine'
import type { AuditEvent } from '../domain/types'
import type { AiEvaluation, WorkflowState } from '../domain/workflow'
import { analyzeAppeal, approveAiEvaluation, approveAssignmentRun, approveCapacityOverride, decideAppeal, executeAppealChange, generateAiEvaluations, getCycle, getCycleCatalog, getWorkflow, listAuditEvents, publishAssignments, runAssignment, transitionCycle } from './firebaseApi'
import { AppealDetails } from './AppealDetails'
import { StudentRoster } from './StudentRoster'
import { useConfirmAction, useUnsavedChanges } from './interaction'

const statusLabels: Record<CycleStatus, string> = { draft: 'טיוטה', choice_open: 'בחירה פתוחה', choice_closed: 'בחירה סגורה', assignment: 'בתהליך שיבוץ', published: 'פורסם', appeals: 'תקופת ערעורים', closed: 'נסגר' }
const actions: Partial<Record<CycleStatus, { to: CycleStatus; label: string; reason: string }>> = {
  draft: { to: 'choice_open', label: 'פתיחת הבחירה', reason: 'פתיחת הבחירה בידי רכז' }, choice_open: { to: 'choice_closed', label: 'סגירת הבחירה', reason: 'סיום תקופת הבחירה' }, choice_closed: { to: 'assignment', label: 'מעבר לשיבוץ', reason: 'פלטי AI נבדקו והקלט מוכן לשיבוץ' }, published: { to: 'appeals', label: 'פתיחת ערעורים', reason: 'פתיחת חלון הערעורים' }, appeals: { to: 'closed', label: 'סגירת המחזור', reason: 'סיום הטיפול בערעורים' },
}
const auditLabels: Record<string, string> = {
  'cycle.created': 'מחזור נוצר', 'catalog.saved': 'הקורסים נשמרו', 'cycle.transitioned': 'מצב המחזור השתנה',
  'preference.draft.saved': 'טיוטת בחירה נשמרה', 'preference.submitted': 'טופס בחירה הוגש', 'ai.batch.generated': 'הערכות נוצרו',
  'ai.evaluation.approved': 'הערכת העדפות אושרה', 'assignment.run.executed': 'השיבוץ הורץ', 'assignment.run.approved': 'השיבוץ אושר',
  'assignment.published': 'השיבוץ פורסם', 'appeal.submitted': 'ערעור הוגש', 'appeal.impact_analyzed': 'השפעת ערעור נבדקה',
  'appeal.recommended': 'נשמרה המלצה לערעור', 'appeal.approved': 'ערעור אושר כהצעה', 'appeal.rejected': 'ערעור נדחה',
  'appeal.capacity_override.approved': 'חריגת קיבולת אושרה', 'appeal.change.executed': 'שינוי בעקבות ערעור בוצע',
}
async function loadWorkspace(cycleId: string) { const [cycle, audits, workflow, catalog] = await Promise.all([getCycle(cycleId), listAuditEvents(), getWorkflow(cycleId, 'coordinator'), getCycleCatalog(cycleId)]); return { cycle, audits, workflow, catalog } }

function EvaluationEditor({ evaluation, cycleId, clusterLabel, onSaved }: { evaluation: AiEvaluation; cycleId: string; clusterLabel: string; onSaved: (workflow: WorkflowState) => void }) {
  const readOnly = useReadOnly()
  const [priority, setPriority] = useState<AiPriority>(evaluation.approved?.priority ?? evaluation.raw.priority)
  const [summary, setSummary] = useState(evaluation.approved?.summary ?? evaluation.raw.summary)
  const [pending, setPending] = useState(false)
  const [error, setError] = useState('')
  useUnsavedChanges(priority !== (evaluation.approved?.priority ?? evaluation.raw.priority) || summary !== (evaluation.approved?.summary ?? evaluation.raw.summary) || pending)
  async function save() { if (pending) return; setPending(true); try { onSaved(await approveAiEvaluation(cycleId, evaluation.id, priority, summary)); setError('') } catch { setError('שמירת ההערכה נכשלה. יש לנסות שוב.') } finally { setPending(false) } }
  return <article className="workflow-item">{error && <p role="alert">{error}</p>}<div><strong>מזהה אנונימי: {evaluation.anonymousStudentRef.slice(0, 13)}…</strong><small>{clusterLabel}</small></div><p>{evaluation.input.rationale ?? 'לא נמסר נימוק — הערכה ניטרלית.'}</p><label>עדיפות מאושרת<select disabled={readOnly} value={priority} onChange={(event) => setPriority(event.target.value as AiPriority)}><option value="high">גבוהה</option><option value="medium">בינונית</option><option value="neutral">ניטרלית</option></select></label><label>סיכום לצוות<textarea disabled={readOnly} rows={2} value={summary} onChange={(event) => setSummary(event.target.value)} /></label><button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void save()}>{evaluation.approved ? 'עדכון אישור' : 'אישור פלט'}</button></article>
}

export function CoordinatorWorkflowWorkspace({ cycleId, onCycleChanged }: { cycleId: string; onCycleChanged: () => Promise<void> }) {
  const readOnly = useReadOnly()
  const { confirm, confirmation } = useConfirmAction()
  const [tab, setTab] = useState<'overview' | 'students' | 'evaluations' | 'appeals'>('overview')
  const [appealQuery, setAppealQuery] = useState('')
  const [appealStatus, setAppealStatus] = useState('submitted')
  const [evaluationFilter, setEvaluationFilter] = useState('pending')
  const [evaluationLimit, setEvaluationLimit] = useState(30)
  const [cycleRevision, setCycleRevision] = useState(0)
  const [cycle, setCycle] = useState<AssignmentCycle | null>(null); const [workflow, setWorkflow] = useState<WorkflowState | null>(null); const [audits, setAudits] = useState<AuditEvent[]>([]); const [courseLabels, setCourseLabels] = useState<Record<string, string>>({}); const [clusterLabels, setClusterLabels] = useState<Record<string, string>>({}); const [balancedClusterIds, setBalancedClusterIds] = useState<string[]>([]); const [message, setMessage] = useState('טוען את לוח המחזור…'); const [pending, setPending] = useState(false)
  function applyLoaded(loaded: Awaited<ReturnType<typeof loadWorkspace>>) { setCycle(loaded.cycle); setAudits(loaded.audits); setWorkflow(loaded.workflow); setCourseLabels(Object.fromEntries(loaded.catalog.courses.map((course) => [course.id, course.label]))); setClusterLabels(Object.fromEntries((loaded.catalog.catalog?.clusters ?? []).map((cluster) => [cluster.clusterId, cluster.label]))); setBalancedClusterIds((loaded.catalog.catalog?.clusters ?? []).filter((cluster) => cluster.balanceByClass).map((cluster) => cluster.clusterId)) }
  async function refresh() { try { const loaded = await loadWorkspace(cycleId); applyLoaded(loaded); setCycleRevision((value) => value + 1); setMessage('הנתונים מעודכנים.') } catch { setMessage('רענון הנתונים נכשל. יש לנסות שוב לפני המשך העבודה.') } }
  useEffect(() => { let active = true; void loadWorkspace(cycleId).then((loaded) => { if (active) { applyLoaded(loaded); setMessage('הנתונים מעודכנים.') } }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : 'טעינת המחזור נכשלה') }); return () => { active = false } }, [cycleId])
  async function perform(operation: () => Promise<unknown>, success: string) { if (pending) return; try { setPending(true); await operation(); await refresh(); await onCycleChanged(); setMessage(success) } catch (error) { setMessage(error instanceof Error ? error.message : 'הפעולה נכשלה') } finally { setPending(false) } }
  async function selectTab(next: typeof tab) {
    if (next === tab) return
    if (!window.dispatchEvent(new Event('nativ-before-navigation', { cancelable: true })) && !(await confirm('יש שינויים שלא נשמרו. לעבור ללשונית אחרת?'))) return
    setTab(next)
  }
  async function confirmPerform(operation: () => Promise<unknown>, success: string, question: string) { if (pending || !(await confirm(question))) return; await perform(operation, success) }
  if (!cycle || !workflow) return <section className="workspace-card"><p aria-live="polite">{message}</p></section>
  const action = actions[cycle.status]; const allAiApproved = workflow.aiEvaluations.length > 0 && workflow.aiEvaluations.every((entry) => entry.approved)
  return <section className="workspace-card" aria-labelledby="coordinator-title">
    <div className="workspace-heading"><div><span className="eyebrow">אזור רכז שיבוץ</span><h2 id="coordinator-title">לוח המחזור</h2></div><span className="status-pill">{statusLabels[cycle.status]}</span></div><p className="workspace-message" aria-live="polite">{message}</p>
    {confirmation}
    <nav className="role-navigation" aria-label="ניהול המחזור">{([['overview', 'תמונת מצב'], ['students', 'תלמידים ובחירות'], ['evaluations', 'בדיקת העדפות'], ['appeals', 'ערעורים']] as const).map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} aria-pressed={tab === id} onClick={() => void selectTab(id)}>{label}</button>)}</nav>
    {tab === 'overview' && <div className="next-action"><h3>דורש טיפול</h3><p>{cycle.status === 'draft' ? 'יש להשלים ולשמור את המקבצים והקורסים לפני פתיחת הבחירה.' : cycle.status === 'choice_open' ? 'תקופת הבחירה פתוחה. אפשר לבדוק מי כבר הגיש ומי עדיין ממתין.' : cycle.status === 'choice_closed' ? (allAiApproved ? 'ההעדפות אושרו. אפשר להתקדם לשיבוץ.' : 'יש להכין ולבדוק את הערכות ההעדפות לפני השיבוץ.') : cycle.status === 'assignment' ? 'יש לבדוק את תוצאות השיבוץ ולאשר אותן לפני הפרסום.' : cycle.status === 'closed' ? 'המחזור הסתיים. אפשר לעיין בבחירות ובשיבוצים.' : 'אפשר לעקוב אחר השיבוצים והערעורים שהתקבלו.'}</p><div className="workspace-actions"><button className="secondary-action" onClick={() => setTab('students')}>צפייה בתלמידים</button>{cycle.status === 'choice_closed' && !allAiApproved && <button className="primary-action" onClick={() => setTab('evaluations')}>בדיקת העדפות</button>}{workflow.appeals.some((entry) => entry.status === 'submitted' || entry.status === 'approved_pending_execution') && <button className="primary-action" onClick={() => setTab('appeals')}>טיפול בערעורים</button>}</div></div>}
    {tab === 'students' && <StudentRoster cycleId={cycleId} courseLabels={courseLabels} clusterLabels={clusterLabels} revision={cycleRevision} />}
    <dl className="workspace-metrics"><div><dt>שנת לימודים</dt><dd>{cycle.schoolYear}</dd></div><div><dt>תקופה</dt><dd>{cycle.termLabel}</dd></div><div><dt>הערכות AI שאושרו</dt><dd>{workflow.aiEvaluations.filter((entry) => entry.approved).length}/{workflow.aiEvaluations.length}</dd></div><div><dt>ערעורים</dt><dd>{workflow.appeals.length}</dd></div></dl>
    {tab === 'evaluations' && ['choice_closed', 'assignment'].includes(cycle.status) && <div className="workflow-section"><div className="section-heading compact"><div><h3>בדיקה ואישור לפני השיבוץ</h3></div>{!workflow.aiBatchCreatedAt && <button type="button" className="primary-action" disabled={readOnly || pending} onClick={() => void perform(() => generateAiEvaluations(cycleId), 'ההערכות נוצרו ומוכנות לבדיקה.')}>יצירת הערכות</button>}</div>{pending && <p role="status">מכין הערכות. הפעולה עשויה להימשך כמה דקות.</p>}<label>הצגת הערכות<select value={evaluationFilter} onChange={(event) => { setEvaluationFilter(event.target.value); setEvaluationLimit(30) }}><option value="pending">ממתינות לאישור</option><option value="all">כל ההערכות</option></select></label>{workflow.aiEvaluations.filter((entry) => evaluationFilter === 'all' || !entry.approved).slice(0, evaluationLimit).map((evaluation) => <EvaluationEditor key={evaluation.id} evaluation={evaluation} cycleId={cycleId} clusterLabel={clusterLabels[evaluation.clusterId] ?? 'מקבץ'} onSaved={(updated) => { setWorkflow(updated); setMessage('ההערכה נשמרה.') }} />)}{workflow.aiEvaluations.filter((entry) => evaluationFilter === 'all' || !entry.approved).length > evaluationLimit && <button className="secondary-action" onClick={() => setEvaluationLimit((value) => value + 30)}>הצגת הערכות נוספות</button>}</div>}
    {tab === 'overview' && cycle.status === 'assignment' && <div className="workflow-section"><h3>הרצת שיבוץ</h3>{!workflow.assignmentRun ? <button type="button" className="primary-action" disabled={readOnly || !allAiApproved || pending} onClick={() => void perform(() => runAssignment(cycleId), 'השיבוץ הושלם והתוצאות מוכנות לבדיקה.')}>הרצת השיבוץ</button> : <><p>{workflow.assignmentRun.assignments.length} שיבוצים · {workflow.assignmentRun.warnings.length} אזהרות</p><button className="secondary-action" onClick={() => setTab('students')}>צפייה בשיבוץ לפי תלמיד, כיתה וקורס</button>{balancedClusterIds.length > 0 && <div className="class-balance-summary"><h4>פיזור לפי כיתות</h4>{balancedClusterIds.map((clusterId) => <section key={clusterId}><strong>{clusterLabels[clusterId] ?? 'מקבץ'}</strong>{[...new Set(workflow.assignmentRun!.assignments.filter((entry) => entry.clusterId === clusterId).map((entry) => entry.courseId))].map((courseId) => { const entries = workflow.assignmentRun!.assignments.filter((entry) => entry.clusterId === clusterId && entry.courseId === courseId && entry.studentClassLabel); const counts = entries.reduce<Record<string, number>>((result, entry) => ({ ...result, [entry.studentClassLabel!]: (result[entry.studentClassLabel!] ?? 0) + 1 }), {}); return <p key={courseId}><b>{courseLabels[courseId] ?? 'קורס'}:</b> {Object.entries(counts).length ? Object.entries(counts).map(([classLabel, count]) => `${classLabel} — ${count}`).join(' · ') : 'לא נמצאו נתוני כיתה'}</p> })}</section>)}</div>}{workflow.assignmentRun.warnings.length > 0 && <ul className="warning-list">{workflow.assignmentRun.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>}{!workflow.assignmentRun.approvedAt ? <button type="button" className="primary-action" disabled={readOnly || pending} onClick={() => void perform(() => approveAssignmentRun(cycleId), 'השיבוץ אושר ומוכן לפרסום.')}>אישור השיבוץ</button> : <button type="button" className="primary-action" disabled={readOnly || pending} onClick={() => void confirmPerform(() => publishAssignments(cycleId), 'השיבוץ פורסם והדיווחים הוכנו לשליחה.', 'לפרסם את השיבוץ? התלמידים יוכלו לראות אותו ויוכנו הודעות לשליחה.')}>פרסום השיבוץ</button>}</>}</div>}
    {tab === 'appeals' && <div className="workflow-section"><h3>ערעורים ושינויים מוצעים</h3><div className="filter-bar"><label>חיפוש בתוכן הערעור<input value={appealQuery} onChange={(event) => setAppealQuery(event.target.value)} /></label><label>מצב<select value={appealStatus} onChange={(event) => setAppealStatus(event.target.value)}><option value="">כל הערעורים</option><option value="submitted">ממתינים להחלטה</option><option value="approved_pending_execution">ממתינים לביצוע</option><option value="executed">בוצעו</option><option value="rejected">נדחו</option></select></label></div>{!workflow.appeals.length && <p>לא התקבלו ערעורים במחזור זה.</p>}{workflow.appeals.filter((entry) => (!appealStatus || entry.status === appealStatus) && (!appealQuery || entry.reason.includes(appealQuery))).map((appeal) => <article className="appeal-card" key={appeal.id}><AppealDetails appeal={appeal} />{!appeal.analysis && <button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void perform(() => analyzeAppeal(cycleId, appeal.id), 'ניתוח ההשפעה נשמר.')}>ניתוח השפעה</button>}{appeal.analysis && appeal.status === 'submitted' && <div className="workspace-actions"><button type="button" className="primary-action" disabled={readOnly || pending || appeal.analysis.constraintViolations.some((violation) => !violation.includes('קיבולת המרבית'))} onClick={() => void perform(() => decideAppeal(cycleId, appeal.id, 'approved'), 'הערעור אושר כהצעה בלבד; השיבוץ טרם השתנה.')}>אישור הערעור כהצעה</button><button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void perform(() => decideAppeal(cycleId, appeal.id, 'rejected'), 'הערעור נדחה ותועד.')}>דחייה</button></div>}{appeal.status === 'approved_pending_execution' && appeal.analysis?.requiresMovingAnotherStudent && !appeal.capacityOverride && <button type="button" className="secondary-action" disabled={readOnly || pending} onClick={() => void perform(() => approveCapacityOverride(cycleId, appeal.id), 'אישור חריגת הקיבולת נשמר. רכז אחר יוכל לבצע את השינוי.')}>אישור חריגת קיבולת</button>}{appeal.status === 'approved_pending_execution' && (!appeal.analysis?.requiresMovingAnotherStudent || appeal.capacityOverride) && <button type="button" className="primary-action" disabled={readOnly || pending} onClick={() => void confirmPerform(() => executeAppealChange(cycleId, appeal.id, workflow.version), 'השינוי בוצע. הדיווחים הועברו למזכירות ולתלמיד.', 'לבצע את השינוי המאושר בשיבוץ ולשלוח את הדיווחים?')}>אישור מפורש וביצוע השינוי</button>}</article>)}</div>}
    <div className="workspace-actions">{tab === 'overview' && action && <button type="button" className="primary-action" disabled={readOnly || pending || (cycle.status === 'choice_closed' && !allAiApproved)} onClick={() => void confirmPerform(() => transitionCycle(cycle, action.to, action.reason), `הפעולה “${action.label}” בוצעה ונשמרה.`, `לבצע ${action.label}? מצב המחזור ישתנה עבור המשתמשים.`)}>{action.label}</button>}<button type="button" className="secondary-action" onClick={() => void refresh()}>רענון נתונים</button></div>
    <details className="audit-preview"><summary>פעולות אחרונות</summary>{audits.length ? <ol>{audits.slice(0, 5).map((event) => <li key={event.id}><strong>{auditLabels[event.action] ?? 'פעולה במערכת'}</strong><span>{new Date(event.occurredAt).toLocaleString('he-IL')}</span>{event.reason && <small>{event.reason}</small>}</li>)}</ol> : <p>עדיין לא נרשמו פעולות.</p>}</details>
  </section>
}
