import { useEffect, useState } from 'react'
import { downloadCycleDocument, getInstructorWorkspace, type InstructorWorkspaceData } from './firebaseApi'
import { todayWeekdayIsrael, weekdayNames, weeklySlotLabel } from '../domain/weeklySlot'

export function InstructorWorkspace({ cycleId }: { cycleId: string }) {
  const [data, setData] = useState<InstructorWorkspaceData | null>(null)
  const [message, setMessage] = useState('טוען את הקורסים שלך…')
  async function refresh() { try { const loaded = await getInstructorWorkspace(cycleId); setData(loaded); setMessage('הנתונים מעודכנים.') } catch { setMessage('רענון הקורסים נכשל. אפשר לנסות שוב.') } }
  useEffect(() => { let active = true; void getInstructorWorkspace(cycleId).then((loaded) => { if (active) { setData(loaded); setMessage('הנתונים מעודכנים.') } }).catch((error: unknown) => { if (active) setMessage(error instanceof Error ? error.message : 'טעינת הקורסים נכשלה') }); return () => { active = false } }, [cycleId])
  const today = todayWeekdayIsrael()
  const sorted = [...(data?.courses ?? [])].sort((left, right) => (left.weeklySlot?.weekday ?? 8) - (right.weeklySlot?.weekday ?? 8) || (left.weeklySlot?.periodStart ?? 0) - (right.weeklySlot?.periodStart ?? 0))
  return <section className="workspace-card" aria-labelledby="instructor-title"><div className="workspace-heading"><div><span className="eyebrow">אזור מנחה</span><h2 id="instructor-title">הקורסים שלי</h2></div></div><p className="workspace-message" aria-live="polite">{message}</p>{data && !data.courses.length && <p>לא נמצאו קורסים המשויכים אליך במחזור זה.</p>}{data && <section className="daily-course-panel"><h3>היום · {weekdayNames[today]}</h3>{sorted.filter(course => course.weeklySlot?.weekday === today).length ? sorted.filter(course => course.weeklySlot?.weekday === today).map(course => <p key={course.id}><strong>{course.label}</strong> · {weeklySlotLabel(course.weeklySlot)} · {course.students.length} תלמידים</p>) : <p>אין לך קורסי בחירה מתוזמנים היום.</p>}</section>}{data?.documentUrl && <p><a href={data.documentUrl} target="_blank" rel="noopener noreferrer">תקצירי הקורסים ↗</a></p>}{data?.hasWordDocument && <button type="button" className="secondary-action" onClick={() => void downloadCycleDocument(cycleId).catch(() => setMessage('פתיחת המסמך נכשלה. בקשו מהרכז לבדוק את הקובץ.'))}>הורדת תקצירי הקורסים</button>}<h3>הלוח השבועי ורשימות התלמידים</h3>{sorted.map((course) => <article className="workflow-item instructor-course-card" key={course.id}><div><strong>{course.label}</strong><small>{weeklySlotLabel(course.weeklySlot)}</small>{course.subjectArea && <small>{course.subjectArea}</small>}</div>{course.description && <details><summary>פרטי הקורס</summary><p>{course.description}</p></details>}<details><summary>תלמידים בקורס · {course.students.length}</summary>{course.students.length ? <ul>{course.students.map((student, index) => <li key={`${student}-${index}`}>{student}</li>)}</ul> : <p>רשימת התלמידים תהיה זמינה לאחר פרסום השיבוץ.</p>}</details></article>)}<button type="button" className="secondary-action" onClick={() => void refresh()}>רענון</button></section>
}
